ayasofyazilim-clomerce/ayasofyazilim-core-project

apps/web/src/app/[lang]/(main)/layout.tsx
Add language selector to main layout:
=> feat: add locale layout

apps/web/src/app/[lang]/(main)/layout.tsx, apps/web/src/app/api/profile/myprofile/route.ts
fix few issues related to hydration in locales in the layout, 
set language with use state
add profile 
redirect on logout and update submodule
=> fix: hydration for locales in layout

apps/web/src/components/language-selector/index.tsx
=> refactor:(localization) LeptonX resource replaced with AbpUi resource

apps/web/src/app/[lang]/(main)/layout.tsx, apps/web/src/app/[lang]/(main)/projects/page.tsx
=> feat:(projects) projects page added

apps/web/src/middleware.ts
This PR allows to check if the URL is public and the user is authenticated, if they are not then it will redirect to login page.
=> feat: add authentication check

apps/web/src/app/[lang]/(main)/projects/page.tsx
=> add: projects page

apps/web/src/middleware.ts
=> feat: add query params support to middleware

apps/web/src/app/[lang]/(main)/layout.tsx, apps/web/src/utils.ts
=> feat: add base url to links (menu links etc.)

apps/web/src/app/[lang]/(main)/profile/layout.tsx
=> style: minor change

apps/web/src/app/[lang]/(main)/layout.tsx
=> fix: component errors

apps/web/src/components/language-selector/index.tsx
if selected locale is same with previous locale dont do anyting
=> fix:language-selector

.vscode/launch.json, apps/web/src/middleware.ts
In this PR I have added a VsCode debugging options and fixed the middleware issue 
fix #51
=> fix: middleware redirecting

apps/web/src/app/[lang]/(main)/layout.tsx, apps/web/src/app/[lang]/(main)/profile/page.tsx, apps/web/src/app/[lang]/(main)/settings/layout.tsx, apps/web/src/app/[lang]/(main)/settings/page.tsx, apps/web/src/app/[lang]/(main)/settings/profile/page.tsx, apps/web/src/app/[lang]/(main)/settings/test/page.tsx, apps/web/src/app/api/settings/profile/route.ts
=> feat: add settings page

apps/web/src/app/[lang]/(main)/layout.tsx
=> fix: config api call fails on subfolders

apps/web/package.json, apps/web/src/app/[lang]/(main)/dashboard/columns.tsx, apps/web/src/app/[lang]/(main)/dashboard/data.ts, apps/web/src/app/[lang]/(main)/dashboard/page.tsx, pnpm-lock.yaml
this PR create and add tables to the dashboard, the tables is not dynamic yet. 
Related https://github.com/ayasofyazilim-clomerce/ayasofyazilim-ui/pull/109
=> feat: add tables

apps/public_web/src/providers/auth.tsx, apps/public_web/src/utils.ts, apps/web/src/providers/auth.tsx, apps/web/src/utils.ts
This PR updates the getbase link to use one unified function
=> refactor: utils purify base link function

apps/web/auth.ts, apps/web/src/app/[lang]/(main)/dashboard/page.tsx, apps/web/src/app/api/admin/route.ts, apps/web/src/lib.ts
First iteration of creating element through the table
This PR allows you to create an element through the table and add it's related objects to use
=> feat: add identity client

apps/web/next.config.js, apps/web/src/app/api/admin/route.ts, apps/web/src/app/api/config/route.ts, apps/web/src/app/api/profile/myprofile/route.ts, apps/web/src/app/api/settings/profile/route.ts, apps/web/src/lib.ts
get updated token to use for API requests, this enables the user to get the data when they log in after a long time.
=> fix: use AuthJs getToken function

apps/web/src/app/[lang]/(main)/dashboard/page.tsx, apps/web/src/utils.ts
Implement the loading state from the UI library. 
Related to: https://github.com/ayasofyazilim-clomerce/ayasofyazilim-ui/pull/144
Closes https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/108
=> feat: add loading state to the table

apps/public_web/src/app/[lang]/(main)/projects/[projectId]/page.tsx, apps/public_web/src/app/[lang]/(main)/projects/demo-data.tsx, apps/public_web/src/app/[lang]/(main)/projects/page.tsx
Resources added.
Layout changes.
=> feat:project & project details pages

apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx, apps/web/src/app/api/admin/[data]/route.ts
=> feat(page): add users

apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx, apps/web/src/app/[lang]/(main)/settings/profile/page.tsx, apps/web/src/app/api/admin/[data]/route.ts, apps/web/src/lib.ts, apps/web/src/providers/providers.tsx
In this pull request I am adding the toaster message to data API which handles the calls and return the message from the server. 
https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/assets/18273833/ad52ec75-2a73-4a34-9ee5-673d4a4e9774
Closes https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/131
=> feat(data-tables): handle data API messages with toast

apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx, apps/web/src/app/[lang]/(main)/dashboard/layout.tsx
=> feat: add tables sections

apps/web/src/app/[lang]/(main)/tenant/page.tsx
=> fix:  show options on  edit form

apps/web/auth-action.ts, apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx, apps/web/src/app/[lang]/(main)/dashboard/layout.tsx, apps/web/src/app/[lang]/(main)/layout.tsx, apps/web/src/app/api/admin/[data]/route.ts
This PR adds the ditions table to the dashboard
=> feat: add editions table

docker-compose.yml
=> chore: docker compose

apps/web/src/providers/providers.tsx
fix extra imports that has been generated in the latest merge
=> fix: extra imports

apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx
=> feat: make activationEndDate  dependencies on activationState in tenant

apps/web/src/app/[lang]/(main)/dashboard/data.ts, apps/web/src/app/api/admin/[data]/route.ts, apps/web/src/utils.ts
=> style: handle select type for the tables

apps/web/src/app/[lang]/(main)/dashboard/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/(main)/dashboard/[domain]/layout.tsx, apps/web/src/app/[lang]/(main)/dashboard/data.ts, apps/web/src/app/api/admin/[data]/route.ts, apps/web/src/providers/providers.tsx, packages/ui/src/main-layout/index.tsx
=> feat: handle no action case for tables

apps/web/src/app/[lang]/(main)/dashboard/data.ts, apps/web/src/app/api/admin/[data]/route.ts
=> feat: add textTemplates page

apps/web/src/app/[lang]/(main)/dashboard/data.ts, apps/web/src/app/api/admin/[data]/route.ts
=> feat: add language text page in dashboard page

apps/web/.env.example, apps/web/.github/workflows/playwright.yml, apps/web/.gitignore, apps/web/package.json, apps/web/playwright.config.ts, apps/web/tests-examples/demo-todo-app.spec.ts, apps/web/tests/example.spec.ts, pnpm-lock.yaml
This PR adds simple e2e test and examples, the example only check if we can login to the website or not. 
closes https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/issues/262
=> test: init e2e with minimum examples   

apps/web/src/app/[lang]/app/[type]/profile/[profileId]/loading.tsx, apps/web/src/app/[lang]/app/[type]/profile/form.tsx, apps/web/src/app/[lang]/app/[type]/profile/loading.tsx, apps/web/src/app/[lang]/app/[type]/profile/page.tsx
=> style: loading for backers

.github/workflows/lint.yml
Adds permissions to write for Pull request
=> ci: add pull request permissions

.github/workflows/lint.yml, .github/workflows/release-unirefund.yml, .github/workflows/release-upwithcrowd.yml, .github/workflows/test-web.yml, publish.sh
=> ci: prevent removing ignored files

publish.sh
=> chore: ci do not change ignored files

packages/ui/src/upwithcrowd/hero/index.tsx, packages/ui/src/upwithcrowd/profile-menu/index.tsx
=> style: text align center

packages/ui/src/main-layout/index.tsx, packages/ui/src/upwithcrowd/project/project-page/index.tsx
=> fix: mobile element visible in web

apps/web/src/middleware.ts
=> feat: add return URL to middleware

apps/web/src/app/[lang]/public/[city]/layout.tsx, packages/ui/src/upwithcrowd/profile-menu/index.tsx
=> feat: hide user menu from specific project

apps/web/src/app/[lang]/app/[type]/company/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/layout.tsx, apps/web/src/middleware.ts
=> chore: update ui

apps/web/src/app/[lang]/app/[type]/company/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/data.ts, apps/web/src/app/[lang]/app/[type]/layout.tsx, apps/web/src/app/api/admin/[data]/route.ts, apps/web/src/middleware.ts, pnpm-lock.yaml
On success: 
The menu: 
The link to the page: localhost:300/en/app/admin/dashboard/admin/languages
Note this is not visible on other pages.
=> feat: add set default language to ui

apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/[data]/page.tsx
=> feat: dashboard table export to csv

.github/workflows/lint-main.yml, .github/workflows/lint-pull-requests.yml, .husky/pre-commit, apps/web/.lintstagedrc.js, apps/web/package.json, apps/web/tsconfig.json, package.json, pnpm-lock.yaml
=> ci: add Lint staged to improve DX

apps/web/src/app/[lang]/public/config.ts
=> chore: add Kocaeli & hide İstanbul

.github/workflows/release-upwithcrowd.yml
=> release 0.0.0 (#422)

apps/web/src/app/[lang]/app/[type]/company/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/layout.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/organization/page.tsx, apps/web/src/app/[lang]/app/[type]/layout.tsx, apps/web/src/app/[lang]/app/[type]/product-group/form.tsx, apps/web/src/app/[lang]/app/[type]/product-group/layout.tsx, apps/web/src/app/[lang]/app/[type]/product-group/loading.tsx, apps/web/src/app/[lang]/app/[type]/product-group/page.tsx, apps/web/src/app/[lang]/app/[type]/product-group/table.tsx, apps/web/src/language-data/AbpUiNavigation/navbar.ts, apps/web/src/language-data/AbpUiNavigation/resources/en.json, apps/web/src/language-data/AbpUiNavigation/resources/tr.json
=> feat: add product group page (draft)

apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/[data]/page.tsx, apps/web/src/app/api/admin/[data]/route.ts
=> chore: make tables filterable

apps/web/src/app/[lang]/app/[type]/dashboard/data.ts
=> chore: hide columns on user table

apps/web/src/app/[lang]/app/[type]/company/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/product-group/table.tsx
=> chore: rename types

apps/web/src/app/[lang]/app/[type]/template/preview/page.tsx, apps/web/src/app/[lang]/app/[type]/template/rebate/page.tsx
=> feat: rebate page

apps/web/src/app/[lang]/app/[type]/template/rebate/page.tsx
=> chore: edit icon of deletion button in rebate page

apps/web/src/app/[lang]/app/[type]/charts.tsx, apps/web/src/app/[lang]/app/[type]/company/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/organization/form.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/data.ts, apps/web/src/app/[lang]/app/[type]/investments/page.tsx, apps/web/src/app/[lang]/app/[type]/product-group/table.tsx, apps/web/src/app/[lang]/app/[type]/template/rebate/page.tsx, apps/web/src/app/api/admin/[data]/route.ts
=> feat: add detailed filters to table

.github/workflows/lint-pull-requests.yml, apps/web/src/app/[lang]/app/[type]/details/data.ts
=> fix: type-check for build

apps/web/src/app/[lang]/app/[type]/charts.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/organization/form.tsx, apps/web/src/app/api/admin/[data]/route.ts
=> chore: prettier

.github/workflows/lint-pull-requests.yml, apps/web/.lintstagedrc.js, apps/web/src/app/[lang]/app/[type]/charts.tsx, apps/web/src/app/[lang]/app/[type]/company/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/organization/form.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/organization/page.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/data.ts, apps/web/src/app/api/admin/[data]/route.ts, pnpm-lock.yaml
This PR just runs the lint and type-check
=> fix: type-check and lint

.github/workflows/lint-pull-requests.yml, pnpm-lock.yaml
=> fix(lockfile): revert

apps/web/src/app/api/admin/[data]/route.ts
=> fix: put on admin route

apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/layout.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/data.ts
=> refactor: improve autoform in dashboard page

.github/workflows/lint-pull-requests.yml
=> ci: add cd to web

apps/web/src/app/[lang]/app/[type]/company/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/details/page.tsx, apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/management/data.ts, apps/web/src/app/api/management/[data]/route.ts
=> refactor: Setting page

apps/web/src/app/[lang]/app/[type]/details/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/details/data.ts, apps/web/src/app/[lang]/app/[type]/details/layout.tsx, apps/web/src/app/[lang]/app/[type]/details/page.tsx
This PR allows issue form to handle data and get them from the server.
=> feat(issue-form): add tags props

apps/web/src/app/[lang]/app/[type]/country-settings/[group]/group.tsx, apps/web/src/app/[lang]/app/[type]/country-settings/[group]/page.tsx, packages/ui/src/settings-view/index.tsx
=> fix:country settings logic partialy removed from ui

apps/web/src/app/[lang]/public/landing.tsx
=> fix: image urls

apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/crm/companies/merchants/new/page.tsx, apps/web/src/app/[lang]/app/[type]/crm/data.ts, apps/web/src/app/api/crm/[data]/route.ts, apps/web/src/lib.ts
=> feat: add  pages in companies page

apps/web/src/language-data/AbpUiNavigation/navbar.ts, apps/web/src/language-data/AbpUiNavigation/resources/en.json, apps/web/src/language-data/AbpUiNavigation/resources/tr.json, apps/web/src/language-data/ContractService/index.ts, apps/web/src/language-data/ContractService/resources/en.json, apps/web/src/language-data/ContractService/resources/tr.json
=> feat:ContractService related languages

apps/web/src/app/[lang]/app/[type]/layout.tsx, packages/ui/src/upwithcrowd/profile-menu/index.tsx, packages/ui/src/utils.ts
=> refactor:move language selector to profile menu (dashboard)

.github/workflows/lint-pull-requests.yml
=> ci: update groups

.github/workflows/lint-pull-requests.yml
This reverts commit 6f889c57d14964d30ec88e91b64ef7889ae5a610.
=> Revert "ci: update groups"

.github/workflows/lint-pull-requests.yml
=> ci: install pnpm

apps/web/src/app/[lang]/app/[type]/traveller/page.tsx, apps/web/src/app/[lang]/app/[type]/traveller/table.tsx
=> chore: add traveller page

apps/web/src/app/[lang]/app/[type]/contracts/action.ts, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/[id]/refund-header.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/[id]/refund-rule.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/page.tsx
=> feat:ContractService refund tables

apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/[id]/edit.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/[id]/preview.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/new/new.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/new/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/refund-fees.tsx
=> feat:ContractService Refund Fee start

apps/web/src/app/[lang]/app/[type]/traveller/new/form.tsx, apps/web/src/app/[lang]/app/[type]/traveller/new/page.tsx, apps/web/src/app/[lang]/app/[type]/traveller/table.tsx, apps/web/src/language-data/TravellerService/index.ts, apps/web/src/language-data/TravellerService/resources/en.json, apps/web/src/language-data/TravellerService/resources/tr.json
http://192.168.1.24:3000/tr/app/admin/traveller/new
=> feat: add new traveller page

apps/web/package.json, apps/web/src/app/[lang]/app/[type]/contracts/action.ts, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/[id]/refund-header.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/[id]/refund-rule.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/page.tsx, pnpm-lock.yaml
=> chore:saas update

apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/[id]/template-details.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/new-rebate-template/layout.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/new-rebate-template/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(main)/company-settings/company-settings.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(main)/company-settings/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(main)/templates/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(main)/templates/templates.tsx
=> feat:ContractService Rebate

apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/[id]/edit.tsx, apps/web/src/language-data/ContractService/index.ts
=> fix:ContractService refundFee

apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/details/[id]/form.tsx, apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/details/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/new/page.tsx, apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/schemas.gen.ts, apps/web/src/app/[lang]/app/[type]/crm/data.ts, apps/web/src/app/[lang]/app/[type]/layout.tsx, apps/web/src/language-data/CRMService/index.ts, apps/web/src/language-data/CRMService/resources/en.json, apps/web/src/language-data/CRMService/resources/tr.json
=> refactor: improve the view of crm tables and pages

apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/[id]/template-details.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/new-rebate-template/layout.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/new-rebate-template/new-rebate.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/rebate.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(main)/layout.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(main)/templates/templates.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/[id]/edit.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/layout.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/refund-fees.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/[id]/refund-header.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/[id]/refund-rule.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/page.tsx, apps/web/src/language-data/ContractService/index.ts
=> language: contract service

apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/details/[id]/action.ts, apps/web/src/app/[lang]/app/[type]/layout.tsx
=> chore: remove unused code in crm page

apps/web/src/app/[lang]/app/[type]/contracts/contracts/data.ts, apps/web/src/app/[lang]/app/[type]/contracts/contracts/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/refund-fees.tsx
=> feat:ContractService refund tables & contract

apps/web/src/app/[lang]/app/[type]/contracts/actions/contracts.ts, apps/web/src/app/[lang]/app/[type]/contracts/actions/rebate-tables.ts, apps/web/src/app/[lang]/app/[type]/contracts/actions/refund-tables.ts, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/[id]/template-details.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(main)/templates/templates.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/[id]/edit.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/refund-fees.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/[id]/refund-header.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/[id]/refund-rule.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/page.tsx, apps/web/src/lib.ts
=> feat:actions new action structure

apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/layout.tsx, apps/web/src/language-data/AbpUiNavigation/resources/en.json, apps/web/src/language-data/AbpUiNavigation/resources/tr.json, apps/web/src/language-data/IdentityService/index.ts, apps/web/src/language-data/IdentityService/resources/en.json, apps/web/src/language-data/IdentityService/resources/tr.json
=> translate: identity service

apps/web/package.json, apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/details/[id]/action.ts, apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/details/[id]/form.tsx, apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/new/page.tsx, apps/web/src/app/[lang]/app/[type]/crm/data.ts, apps/web/src/app/api/crm/[data]/route.ts, apps/web/src/utils.ts, pnpm-lock.yaml
=> refactor: crm page

apps/web/src/app/[lang]/app/[type]/details/layout.tsx
=> Style(tag):  remove the left menu

apps/web/src/app/[lang]/app/[type]/dashboard/[domain]/[data]/page.tsx
=> chore: remove comment & translate

apps/web/src/app/[lang]/app/[type]/contracts/actions/contracts.ts, apps/web/src/app/[lang]/app/[type]/contracts/contracts/data.ts, apps/web/src/app/[lang]/app/[type]/contracts/contracts/new-contract/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/contracts/page.tsx, apps/web/src/app/[lang]/app/[type]/crm/actions/merchant.ts, packages/ui/package.json, pnpm-lock.yaml
=> feat: Contract Service - Contract page

apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/rebate.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(main)/company-settings/company-settings.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(main)/templates/templates.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/[id]/refund-header.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/[id]/refund-rule.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/page.tsx, apps/web/src/language-data/ContractService/index.ts, apps/web/src/language-data/ContractService/resources/en.json, apps/web/src/language-data/ContractService/resources/tr.json
=> chore:ContractService

apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/new/page.tsx, apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/schemas.gen.ts, apps/web/src/app/[lang]/app/[type]/crm/data.ts
=> feat: phone input for create crm

apps/web/src/app/[lang]/app/[type]/contracts/contracts/new-contract/page.tsx
=> chore(contract): remove export from page

apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(main)/page.tsx, apps/web/src/app/[lang]/app/[type]/operations/details/page.tsx
=> chore(tags): add related links

apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/page.tsx, apps/web/src/language-data/ContractService/index.ts, apps/web/src/language-data/ContractService/resources/en.json, apps/web/src/language-data/ContractService/resources/tr.json
=> chore:language & pageHeader

apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(main)/page.tsx
=> chore: edit the link for edit in crm page

apps/web/src/app/[lang]/app/[type]/layout.tsx, packages/ui/src/main-layout/index.tsx
=> style:userImage & badge

apps/web/src/app/[lang]/app/[type]/contracts/actions/rebate-tables.ts, apps/web/src/app/[lang]/app/[type]/contracts/contracts/new-contract/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/[id]/template-details.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/new-rebate-template/new-rebate.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/rebate.tsx, apps/web/src/lib.ts
=> feat:(ContractService):RebateTables resource & new rebate template implementation

apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/subcompany/new/page.tsx, apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/new/page.tsx
=> feat: add caution message for email in post form in crm

apps/web/package.json, apps/web/src/app/[lang]/app/[type]/contracts/actions/refund-tables.ts, apps/web/src/app/[lang]/app/[type]/contracts/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/new-rebate-template/new-rebate.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/rebate.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-fees/[id]/edit.tsx, apps/web/src/app/[lang]/app/[type]/contracts/refund/refund-tables/[id]/refund-rule.tsx, pnpm-lock.yaml
=> fix(ContractService): saas update

apps/web/src/app/[lang]/app/[type]/contracts/contracts/new-contract/page.tsx, apps/web/src/app/[lang]/app/[type]/contracts/contracts/page.tsx
=> fix(ContractService): isLoading fix

apps/web/auth-action.ts, apps/web/auth.ts, apps/web/src/app/[lang]/[auth]/page.tsx
=> feat: add tenant login

apps/web/package.json, pnpm-lock.yaml
=> chore: update saas

apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/page.tsx
=> chore(management): add the language to forms

apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/[id]/template-details.tsx, apps/web/src/app/[lang]/app/[type]/contracts/rebate/(alternative)/templates/new-rebate-template/new-rebate.tsx, apps/web/src/app/[lang]/app/[type]/traveller/[travellerId]/form.tsx, apps/web/src/app/[lang]/app/[type]/traveller/[travellerId]/page.tsx, apps/web/src/app/[lang]/app/[type]/traveller/actions.ts, apps/web/src/app/[lang]/app/[type]/traveller/new/form.tsx, apps/web/src/app/[lang]/app/[type]/traveller/table.tsx, apps/web/src/lib.ts, pnpm-lock.yaml
=> feat(traveler): integration with backend

apps/web/src/app/[lang]/app/[type]/crm/[data]/(alternative)/[id]/form.tsx
=> fix: edit the link in new subcompany

apps/web/src/app/[lang]/app/[type]/crm/[data]/(alternative)/[id]/form.tsx, apps/web/src/app/[lang]/app/[type]/crm/[data]/(alternative)/[id]/subcompany/new/page.tsx, apps/web/src/app/[lang]/app/[type]/crm/[data]/(alternative)/new/page.tsx
=> chore: remove unused code and make the primaryflag as true in post forms

apps/web/src/language-data/CRMService/index.ts, apps/web/src/language-data/CRMService/resources/en.json, apps/web/src/language-data/CRMService/resources/tr.json
- [x ] Development
- [ x] Added all translations, no hard coded text.
=> feat: add form of individual in crm page

apps/web/src/app/[lang]/app/[type]/crm/[data]/(main)/layout.tsx
=> fix: edit the name of pages in crm in layout

apps/web/src/app/[lang]/app/[type]/crm/data.ts
=> refactor: use separate formSubPositions for pages in crm

apps/web/src/app/[lang]/app/[type]/crm/[data]/(alternative)/[id]/data.ts, apps/web/src/app/[lang]/app/[type]/crm/[data]/(alternative)/[id]/form.tsx, apps/web/src/app/[lang]/app/[type]/crm/[data]/(alternative)/[id]/individual/new/data.ts, apps/web/src/app/[lang]/app/[type]/crm/data.ts
=> feat: add refine function to control the message of telephone number

.github/workflows/publish-dev.yml, apps/web/src/app/[lang]/app/[type]/layout.tsx
=> feat: add ayshopgo project

apps/web/src/app/[lang]/app/[type]/layout.tsx, apps/web/src/middleware.ts
=> refactor: hide unimportant sections in ayshopgo and tahsilet projects

packages/ui/src/theme/main-admin-layout/components/breadcrumb/index.tsx, packages/ui/src/theme/main-admin-layout/components/logo.tsx, packages/ui/src/theme/main-admin-layout/components/navbar-dropdown/index.tsx, packages/ui/src/theme/main-admin-layout/components/navbar-searchbar/index.tsx, packages/ui/src/theme/main-admin-layout/components/notifications/index.tsx, packages/ui/src/theme/main-admin-layout/components/profile-menu/index.tsx
=> feat: add components for new layout

packages/ui/src/theme/main-admin-layout/components/navbar-searchbar/index.tsx, packages/ui/src/theme/main-admin-layout/components/navbar.tsx, packages/ui/src/theme/main-admin-layout/header-section.tsx
=> feat: add section-layout-v2 to new-layout

packages/ui/src/theme/main-admin-layout/components/navbar-searchbar/index.tsx, packages/ui/src/theme/main-admin-layout/components/navbar.tsx, packages/ui/src/theme/main-admin-layout/components/profile-menu/index.tsx, packages/ui/src/theme/main-admin-layout/header-section.tsx
=> style: navbar

apps/web/src/app/[lang]/app/[type]/customers/(main)/data.ts, apps/web/src/app/[lang]/app/[type]/customers/(main)/layout.tsx, apps/web/src/app/[lang]/app/[type]/customers/(main)/page.tsx, apps/web/src/app/[lang]/app/[type]/customers/[id]/action.ts, apps/web/src/app/[lang]/app/[type]/customers/[id]/data.ts, apps/web/src/app/[lang]/app/[type]/customers/[id]/form.tsx, apps/web/src/app/[lang]/app/[type]/customers/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/customers/new/page.tsx, apps/web/src/app/[lang]/app/[type]/layout.tsx, apps/web/src/language-data/AbpUiNavigation/index.ts, apps/web/src/language-data/AbpUiNavigation/resources/en.json, apps/web/src/language-data/AbpUiNavigation/resources/tr.json, apps/web/src/language-data/CustomersService/index.ts, apps/web/src/language-data/CustomersService/resources/en.json, apps/web/src/language-data/CustomersService/resources/tr.json, apps/web/src/middleware.ts
=> feat: add customers page in ayshopgo project

apps/web/src/app/[lang]/app/[type]/navbar/navbar-data.tsx
=> chore: fix navbar disappearing bug

apps/web/src/language-data/AbpUiNavigation/index.ts, apps/web/src/language-data/AbpUiNavigation/resources/en.json, apps/web/src/language-data/AbpUiNavigation/resources/tr.json
=> chore: add translation for nav

apps/web/src/app/[lang]/app/[type]/layout.tsx, apps/web/src/app/[lang]/app/[type]/navbar/navbar-profile-data.tsx, packages/ui/src/theme/main-admin-layout/components/logo.tsx
=> chore: fix logo on other projects & fix profile menu information

apps/web/src/app/[lang]/app/[type]/navbar/groups.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/[id]/template-details.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/action.ts, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/new/layout.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/new/new-rebate.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/new/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/new/preview/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/rebate.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/templates.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-fees/[id]/edit.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-fees/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-fees/[id]/preview.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-fees/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-fees/refund-fees.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-tables/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-tables/[id]/refund-header.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-tables/[id]/refund-rule.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-tables/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund/action.ts
=> refactor(ContractService): move templates to settings

apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/page.tsx, apps/web/src/language-data/IdentityService/index.ts, apps/web/src/language-data/IdentityService/resources/en.json, apps/web/src/language-data/IdentityService/resources/tr.json
=> fix: show the delete button in action list in management page

apps/web/src/app/[lang]/app/[type]/customers/[id]/form.tsx
=> fix: change typeCode in edit form

apps/web/src/app/[lang]/app/[type]/debtors/(main)/page.tsx, apps/web/src/app/[lang]/app/[type]/debtors/[id]/form.tsx, apps/web/src/app/[lang]/app/[type]/debtors/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/debtors/actions/action.ts, apps/web/src/app/[lang]/app/[type]/debtors/data.ts, apps/web/src/app/[lang]/app/[type]/debtors/new/page.tsx, apps/web/src/app/[lang]/app/[type]/navbar/navbar-data.tsx, apps/web/src/app/[lang]/app/[type]/navbar/projects/tahsilet.tsx, apps/web/src/language-data/AbpUiNavigation/index.ts, apps/web/src/language-data/AbpUiNavigation/resources/en.json, apps/web/src/language-data/AbpUiNavigation/resources/tr.json, apps/web/src/language-data/DebtorsService/index.ts, apps/web/src/language-data/DebtorsService/resources/en.json, apps/web/src/language-data/DebtorsService/resources/tr.json, apps/web/src/middleware.ts
=> feat: add debtors page in tahsilet project

packages/ui/src/theme/main-admin-layout/components/navbar-searchbar/index.tsx
=> chore: remove searchbar unwanted character

apps/web/src/app/[lang]/app/[type]/crm/[data]/[id]/individual/new/layout.tsx, apps/web/src/app/[lang]/app/[type]/crm/[data]/[id]/subcompany/new/layout.tsx, apps/web/src/app/[lang]/app/[type]/debtors/[id]/form.tsx, apps/web/src/app/[lang]/app/[type]/debtors/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/debtors/new/form.tsx, apps/web/src/app/[lang]/app/[type]/debtors/new/page.tsx, packages/ui/src/theme/main-admin-layout/header-section.tsx
=> feat: override page title & description & back link

apps/web/src/app/[lang]/app/[type]/crm/[data]/[id]/individual/new/layout.tsx, apps/web/src/app/[lang]/app/[type]/crm/[data]/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/crm/[data]/[id]/subcompany/new/layout.tsx
=> chore: override page title & description on sub pages

apps/web/src/app/[lang]/app/[type]/crm/[data]/[id]/form.tsx, apps/web/src/app/[lang]/app/[type]/crm/[data]/[id]/individual/new/layout.tsx, apps/web/src/app/[lang]/app/[type]/crm/[data]/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/crm/[data]/[id]/subcompany/new/layout.tsx, apps/web/src/language-data/CRMService/index.ts, apps/web/src/language-data/CRMService/resources/en.json, apps/web/src/language-data/CRMService/resources/tr.json
=> refactor: add languge in all pages in crm 

apps/web/src/fetch.ts
=> feat: add GlobalFetch<T>

apps/web/src/app/[lang]/app/[type]/crm/[data]/[id]/form.tsx, apps/web/src/app/[lang]/app/[type]/crm/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/product/[data]/page.tsx
=> chore: fix typo of tableAction -> componentType

apps/web/src/app/[lang]/app/[type]/crm/[data]/[id]/form.tsx, apps/web/src/app/[lang]/app/[type]/crm/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/product/[data]/page.tsx
=> chore: remove unused title prop on TableActionConfirmation

apps/web/src/language-data/CustomersService/index.ts, apps/web/src/language-data/DebtorsService/index.ts, apps/web/src/language-data/ProjectService/index.ts, apps/web/src/language-data/SettingService/index.ts, apps/web/src/language-data/language-data.ts
=> refactor: add LanguageDataResourceType & rename some of resources

apps/web/src/app/[lang]/app/[type]/crm/traveller/actions.ts, apps/web/src/app/[lang]/app/[type]/crm/traveller/table.tsx
=> feat(traveler): enable pagination

apps/web/src/table/table-utils.ts
=> feat: add reusable column & row actions (edit & delete) 

apps/web/src/app/[lang]/app/[type]/crm/traveller/new/form.tsx, apps/web/src/app/[lang]/app/[type]/crm/traveller/table.tsx
=> feat: add create traveller

apps/web/.eslintrc.js, apps/web/src/app/[lang]/app/[type]/action.ts, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/action.ts, apps/web/src/app/[lang]/app/[type]/parties/table-data.tsx, apps/web/tsconfig.json, packages/ui/utils/table/form-schemas.ts, pnpm-lock.yaml
=> feat: make party actions generic with type

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/page.tsx, packages/ui/utils/table/table-utils.ts
=> feat: add create parties page

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new-data/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new-data/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/table-data.tsx, packages/ui/utils/table/table-utils.ts
=> feat: add getTableDataServerSide & deleteTableRowServerSide & remove client versions & add easy new-data

apps/web/package.json, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new-data/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/table-data.tsx, packages/ui/package.json, packages/ui/utils/table/form-schemas.ts, packages/ui/utils/table/table-utils.ts, pnpm-lock.yaml
=> feat: add addressSchemaByData &getEnumName &  rename dto

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/action.ts, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/types.ts, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/update-data.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/page.tsx
=> feat: add parties edit page

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/update-data.tsx, apps/web/src/app/[lang]/app/[type]/parties/table-data.tsx
=> chore: generic organizationSchemaSubPositions&export subposition

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/action.ts, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/update-data.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/action.ts, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new-data/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new-data/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/table-data.tsx, apps/web/src/app/[lang]/app/[type]/parties/types.ts
=> chore: table data move types to types.ts & fix imports

apps/web/src/middleware.ts
=> feat: add searchparams to middleware

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/action.ts, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/table-data.tsx
=> feat: add getPartySubTableData to parties & add subEntityType 

apps/web/src/app/[lang]/app/[type]/crm/traveller/new/form.tsx
=> fix(traveller): edit the translation function 

apps/web/src/app/[lang]/app/[type]/settings/product/[data]/page.tsx, apps/web/src/language-data/SettingService/index.ts, apps/web/src/language-data/SettingService/resources/en.json, apps/web/src/language-data/SettingService/resources/tr.json
=> feat: add translation to forms in setting page

apps/web/src/language-data/SettingService/index.ts, apps/web/src/language-data/SettingService/resources/en.json, apps/web/src/language-data/SettingService/resources/tr.json
=> refactor(setting): translation

apps/web/src/language-data/TravellerService/index.ts, apps/web/src/language-data/TravellerService/resources/en.json, apps/web/src/language-data/TravellerService/resources/tr.json
=> feat(traveller): add translation of enum

apps/web/src/app/[lang]/app/[type]/crm/traveller/table.tsx, apps/web/src/language-data/TravellerService/index.ts, apps/web/src/language-data/TravellerService/resources/en.json, apps/web/src/language-data/TravellerService/resources/tr.json
=> feat(traveller): add filter and translation to it

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new/crm/individual/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new/crm/organization/form.tsx
=> refactor(merchant): edit the create form of organization and individual

apps/web/src/app/[lang]/app/[type]/management/data.ts, apps/web/src/app/api/admin/[data]/route.ts
=> feat(dashboard):  add filter to some pages

apps/web/package.json, apps/web/src/app/[lang]/app/[type]/operations/details/actions.ts, apps/web/src/app/[lang]/app/[type]/operations/details/add/page.tsx, apps/web/src/app/[lang]/app/[type]/operations/details/page.tsx, pnpm-lock.yaml
=> feat(tags): add tags summary

apps/web/src/language-data/CRMService/resources/en.json, apps/web/src/language-data/CRMService/resources/tr.json, apps/web/src/language-data/ContractService/resources/tr.json
=> chore(Contract): resources

apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/table-data.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/table.tsx, apps/web/src/app/[lang]/app/actions/table.ts, packages/ui/src/TableComponent/index.tsx
=> feat: add filter to table comment & make deleteRequest optional

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/action.ts, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/new/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/new/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/[id]/template-details.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/new/new-rebate.tsx, apps/web/src/app/[lang]/app/actions/table.ts, apps/web/src/lib.ts, pnpm-lock.yaml
This is an entry of contracts on merchants, will be updated asap.
=> feat(Contract):new contract & list contracts 

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/page.tsx
=> fix(Contract): build errors

apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/rebate.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-fees/refund-fees.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-tables/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-tables/[id]/refund-header.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-tables/[id]/refund-rule.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-tables/page.tsx
=> chore(Templates): refund & rebate tables style & cleanup

apps/web/src/app/[lang]/app/[type]/operations/details/add/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/new/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/individuals-table/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/subcompanies-table/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/page.tsx, apps/web/src/app/[lang]/app/actions/CrmService/actions.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts
=> refactor:rename table.ts with api-requests&add CrmService actions

apps/web/src/app/[lang]/app/[type]/management/data.ts
- [] Added all translations, no hard coded text.
=> fix(management): make the value as empty when type is select

apps/web/src/app/[lang]/app/actions/CrmService/actions.ts, packages/ui/src/TableComponent/index.tsx, packages/ui/utils/table/table-utils.ts
You can add multiple custom dialog to the table component.
=> feat: add custom dialog action to table component

apps/web/src/app/[lang]/app/actions/ContractService/action.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts
=> refactor(Contract): api-requests & use server

apps/web/src/app/[lang]/app/actions/ContractService/action.ts, apps/web/src/app/[lang]/app/actions/CrmService/actions.ts, apps/web/src/app/[lang]/app/actions/LocationService/actions.ts
=> chore: simplfy actions

apps/web/src/app/[lang]/app/[type]/parties/traveller/data.ts, apps/web/src/app/[lang]/app/[type]/parties/traveller/new/form.tsx, apps/web/src/app/[lang]/app/actions/LocationService/actions.ts, apps/web/src/app/[lang]/app/actions/LocationService/schemas.tsx, packages/ui/package.json, packages/ui/src/select-merchant/index.tsx, packages/ui/utils/table/form-schemas.ts, pnpm-lock.yaml
=> chore: update package lock & ui & types (related to saas) & prevent undefined api calls on handleOnAddressValueChange

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/address/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/page.tsx, apps/web/src/app/[lang]/app/actions/LocationService/schemas.tsx
=> refactor: crm update address

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new/crm/individual/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new/crm/organization/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new/individual/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new/page-client.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/new/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/table-data.tsx, apps/web/src/app/[lang]/app/actions/LocationService/schemas.tsx
=> chore: ask taxOfficeId when creating refund points & add hideAddressFields function to Location Service schema

apps/web/package.json, apps/web/src/app/[lang]/app/[type]/navbar/groups.tsx, apps/web/src/app/[lang]/app/[type]/navbar/projects/unirefund.tsx, apps/web/src/app/[lang]/app/[type]/operations/export-validation/[exportId]/form.tsx, apps/web/src/app/[lang]/app/[type]/operations/export-validation/[exportId]/page.tsx, apps/web/src/app/[lang]/app/[type]/operations/export-validation/new/form.tsx, apps/web/src/app/[lang]/app/[type]/operations/export-validation/new/page.tsx, apps/web/src/app/[lang]/app/[type]/operations/export-validation/page.tsx, apps/web/src/app/[lang]/app/actions/CrmService/actions.ts, apps/web/src/app/[lang]/app/actions/ExportValidationService/actions.ts, apps/web/src/app/[lang]/app/actions/ExportValidationService/post-actions.ts, apps/web/src/app/[lang]/app/actions/ExportValidationService/put-actions.ts, apps/web/src/app/[lang]/app/actions/TagService/actions.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts, apps/web/src/language-data/AbpUiNavigation/resources/en.json, apps/web/src/language-data/AbpUiNavigation/resources/tr.json, apps/web/src/language-data/ExportValidationService/index.ts, apps/web/src/language-data/ExportValidationService/resources/en.json, apps/web/src/language-data/ExportValidationService/resources/tr.json, apps/web/src/lib.ts, pnpm-lock.yaml
=> feat(Export Validation): add Export Validation page in operation section

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/address/form.tsx, apps/web/src/app/[lang]/app/actions/LocationService/schemas.tsx, apps/web/src/app/[lang]/app/actions/LocationService/use-address-hook.tsx.tsx
=> feat: add useAddressHook

apps/web/src/app/[lang]/app/[type]/operations/export-validation/[exportId]/form.tsx, apps/web/src/app/[lang]/app/[type]/operations/export-validation/new/form.tsx, apps/web/src/language-data/Default/resources/en.json, apps/web/src/language-data/Default/resources/tr.json, apps/web/src/language-data/ExportValidationService/resources/en.json, apps/web/src/language-data/ExportValidationService/resources/tr.json
=> chore(expot validation): add translation functions to add and update forms

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/organization/form.tsx, apps/web/src/app/[lang]/app/actions/CrmService/put-actions.ts, apps/web/src/app/[lang]/app/actions/CrmService/types.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts
=> feat(crm): add putCrmOrganizationApi & use it

apps/web/src/app/[lang]/app/[type]/operations/details/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/utils.ts
=> fix: build traveller page

apps/web/package.json, pnpm-lock.yaml
=> chore(saas): account, administration, identity

apps/web/src/app/[lang]/app/actions/LocationService/schemas.tsx, apps/web/src/app/[lang]/app/actions/LocationService/use-address-hook.tsx.tsx
=> fix: regionList not updating when country change

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/personal-summaries/form.tsx, apps/web/src/app/[lang]/app/actions/CrmService/put-actions.ts, apps/web/src/app/[lang]/app/actions/CrmService/types.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts
=> feat(crm): add putCrmIndividualPersonalSummaryApi & use it

apps/web/package.json, apps/web/src/app/[lang]/app/[type]/operations/details/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/new/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/utils.server.ts, apps/web/src/app/[lang]/app/[type]/parties/traveller/utils.ts, apps/web/src/app/[lang]/app/actions/LocationService/utils.ts, apps/web/src/app/[lang]/app/actions/table-utils.ts, packages/ui/src/TableComponent/index.tsx, pnpm-lock.yaml
=> chore(tags): update filters and error messages

apps/web/package.json, apps/web/src/app/[lang]/app/[type]/customers/[id]/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/merchant/form.tsx, pnpm-lock.yaml
=> chore(crm): update saas

apps/web/src/app/[lang]/app/[type]/operations/details/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/operations/details/page.tsx
=> chore(tag/details): use backend

apps/web/src/app/[lang]/app/[type]/operations/details/[id]/page.tsx
=> chore(tag): show name intead of id

apps/web/src/app/[lang]/app/actions/CrmService/actions.ts, apps/web/src/app/[lang]/app/actions/CrmService/post-actions.ts, apps/web/src/app/[lang]/app/actions/CrmService/types.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts, apps/web/src/app/[lang]/app/actions/api-utils-client.ts
=> feat(crm): add postAffiliationsApi & getAffiliationCodeApi & getIndividualsApi

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/individuals-table/table.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/page.tsx, packages/ui/src/TableComponent/index.tsx
=> chore(table-component): move export action to the last

apps/web/package.json, apps/web/src/app/[lang]/app/[type]/operations/details/page.tsx, apps/web/src/app/[lang]/app/[type]/operations/export-validation/page.tsx, apps/web/src/app/[lang]/app/[type]/operations/filter.ts, pnpm-lock.yaml
=> feat(export-validation): add filter 

apps/web/src/app/[lang]/app/[type]/management/data.ts
=> fix(dashboard): convert string to date in filter

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/details.tsx
=> refactor:edit contractheader Autoform to SchemaForm

apps/web/src/app/[lang]/app/actions/LocationService/schemas.tsx, apps/web/src/app/[lang]/app/actions/LocationService/use-address-hook.tsx.tsx
=> feat(AddressHook): compability with SchemaForm

apps/web/src/app/[lang]/app/actions/ContractService/action.ts, apps/web/src/lib.ts
=> chore(actions): add structured response

apps/web/src/app/[lang]/app/[type]/operations/details/add/page.tsx, apps/web/src/app/[lang]/app/[type]/operations/details/page.tsx
=> feat(tags): add links

apps/web/src/app/[lang]/app/[type]/customers/(main)/data.ts, apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/management/data.ts, apps/web/src/types.ts
=> chore(types): remove any and use typed dataconfig

apps/web/src/app/[lang]/app/[type]/customers/(main)/page.tsx, apps/web/src/app/[lang]/app/[type]/debtors/(main)/page.tsx, apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/operations/details/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/product/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-fees/refund-fees.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-tables/[id]/refund-rule.tsx, packages/ui/src/TableComponent/index.tsx
=> chore(tables): update fetch requests

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/details.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/contract-header.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/new/page.tsx, apps/web/src/language-data/ContractService/resources/en.json, apps/web/src/language-data/ContractService/resources/tr.json
=> feat(Contract): default refundTable selection & typesafe form

apps/web/package.json, apps/web/src/app/[lang]/app/[type]/finance/billing/page.tsx, apps/web/src/app/[lang]/app/[type]/navbar/groups.tsx, apps/web/src/app/[lang]/app/[type]/navbar/projects/unirefund.tsx, apps/web/src/app/[lang]/app/actions/FinanceService/actions.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts, apps/web/src/language-data/AbpUiNavigation/resources/en.json, apps/web/src/language-data/AbpUiNavigation/resources/tr.json, apps/web/src/language-data/FinanceService/index.ts, apps/web/src/language-data/FinanceService/resources/en.json, apps/web/src/language-data/FinanceService/resources/tr.json, apps/web/src/lib.ts, pnpm-lock.yaml
=> feat(finance/billing): add finance and billing to the main navigation list and add get  and delete function in billing page

apps/web/src/app/[lang]/app/[type]/management/data.tsx, apps/web/src/app/[lang]/app/actions/IdentityService/put-actions.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts
=> feat(management/application): add Token Lifetime option to the action list

apps/web/src/app/[lang]/app/[type]/management/data.tsx, apps/web/src/app/[lang]/app/actions/SaasService/put-actions.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts
=> feat(tenant/setpassword): add the setPassw0rd option to action list in tenant page

apps/web/src/app/[lang]/app/[type]/management/data.tsx, apps/web/src/app/[lang]/app/actions/IdentityService/put-actions.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts
=> feat(user/two-factor): add two factor option to the action list

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/contract-header.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/contract-widgets.tsx
=> feat(ContractHeader): split contract widgets for later usage

apps/web/package.json, apps/web/src/app/[lang]/app/[type]/finance/billing/[billingId]/form.tsx, apps/web/src/app/[lang]/app/[type]/finance/billing/[billingId]/page.tsx, apps/web/src/language-data/FinanceService/resources/en.json, apps/web/src/language-data/FinanceService/resources/tr.json, pnpm-lock.yaml
=> refactor(finance/billing): add merchantId to the edit form

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/contract-settings.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/details.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/form.tsx, apps/web/src/app/[lang]/app/actions/ContractService/action.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts
=> feat(Contract): contract settings

apps/web/src/app/[lang]/app/[type]/management/data.tsx
=> feat(table): pass trigger data to autoform

apps/web/src/app/[lang]/app/[type]/not-found.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/contract-settings.tsx, apps/web/src/app/[lang]/app/actions/ContractService/action.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts, apps/web/src/language-data/ContractService/resources/en.json, apps/web/src/language-data/ContractService/resources/tr.json
=> feat(ContractSettings): expandable row styles & set default

apps/web/src/app/[lang]/app/[type]/management/data.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/form.tsx, apps/web/src/language-data/ContractService/resources/en.json, apps/web/src/language-data/ContractService/resources/tr.json
=> chore(Contract): table resources

apps/web/src/app/[lang]/app/[type]/management/data.tsx, apps/web/src/app/[lang]/app/actions/IdentityService/actions.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts
=> feat(management/application): add getTokenLifetime function to get the data from backend to autoform

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/contract-header.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/contract-settings.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/details.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/rebate-settings.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/contract-header-form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/new/page.tsx
=> refactor(Contract): split contract sections into components

apps/web/src/app/[lang]/app/[type]/management/data.tsx, apps/web/src/app/[lang]/app/actions/IdentityService/actions.ts, apps/web/src/app/[lang]/app/actions/IdentityService/put-actions.ts, apps/web/src/app/[lang]/app/actions/SaasService/put-actions.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts
=> feat(management/user): add the getTwoFactorEnableApi function to get the data from backend to autoform

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/form.tsx
=> fix: type error

apps/web/src/app/[lang]/app/[type]/navbar/projects/unirefund.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/form.tsx, apps/web/src/app/[lang]/app/[type]/refund/data.tsx
=> chore(refund): add refund to menu & update ui 

apps/web/src/app/[lang]/app/[type]/parties/traveller/new/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/new/page.tsx, apps/web/src/language-data/Default/resources/en.json, apps/web/src/language-data/Default/resources/tr.json
=> refcator(traveller): add control for the data of countries

apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/utils.ts, apps/web/src/app/[lang]/app/actions/TravellerService/actions.ts, apps/web/src/app/[lang]/app/actions/TravellerService/put-actions.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts, apps/web/src/language-data/TravellerService/resources/en.json, apps/web/src/language-data/TravellerService/resources/tr.json
=> feat(traveller): add update to traveller for all sections

apps/web/src/app/[lang]/app/[type]/operations/details/page.tsx, apps/web/src/utils-number.ts
=> feat(utils-number): add localizeCurrency & localizeNumber

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/contract-settings.tsx, apps/web/src/app/[lang]/app/actions/ContractService/action.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts, apps/web/src/language-data/ContractService/resources/en.json, apps/web/src/language-data/ContractService/resources/tr.json
=> feat(Contract):contract settings resources & actions

apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/identification/[identificationId]/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/identification/[identificationId]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/utils.ts, apps/web/src/language-data/TravellerService/resources/en.json, apps/web/src/language-data/TravellerService/resources/tr.json
=> feat(traveller): add the update form for personal identification 

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/contract-settings.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/details.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/page.tsx
=> feat(ContractSettings): create & update & delete

apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/identification/[identificationId]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/page.tsx, apps/web/src/language-data/TravellerService/resources/en.json, apps/web/src/language-data/TravellerService/resources/tr.json
- [x Added all translations, no hard coded text.
=> feat(traveller): add header and description to edit pages

apps/web/src/app/[lang]/app/[type]/refund/data.tsx, apps/web/src/app/[lang]/app/[type]/refund/page.tsx, apps/web/src/app/[lang]/app/[type]/refund/table.tsx, apps/web/src/language-data/Default/resources/en.json, apps/web/src/language-data/Default/resources/tr.json
=> chore(refund): add locale to date & translations

apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/identification/[identificationId]/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/identification/[identificationId]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/identification/new/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/identification/new/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/page.tsx, apps/web/src/language-data/TravellerService/resources/en.json, apps/web/src/language-data/TravellerService/resources/tr.json
=> feat(traveller): add form of create new identification

apps/web/src/app/[lang]/app/[type]/settings/templates/refund-tables/data.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-tables/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-tables/table.tsx, apps/web/src/app/[lang]/app/actions/ContractService/action.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts
=> refactor(templates/refund-tables): serverside

apps/web/auth-action.ts, apps/web/src/lib.ts, turbo.json
=> feat: use tenant id from .env

apps/web/src/app/[lang]/app/actions/ContractService/action.ts, apps/web/src/app/[lang]/app/actions/CrmService/actions.ts, apps/web/src/app/[lang]/app/actions/CrmService/post-actions.ts, apps/web/src/app/[lang]/app/actions/CrmService/put-actions.ts, apps/web/src/app/[lang]/app/actions/ExportValidationService/actions.ts, apps/web/src/app/[lang]/app/actions/ExportValidationService/post-actions.ts, apps/web/src/app/[lang]/app/actions/ExportValidationService/put-actions.ts, apps/web/src/app/[lang]/app/actions/IdentityService/actions.ts, apps/web/src/app/[lang]/app/actions/LocationService/actions.ts, apps/web/src/app/[lang]/app/actions/TagService/actions.ts, apps/web/src/app/[lang]/app/actions/TravellerService/actions.ts, apps/web/src/app/[lang]/app/actions/TravellerService/post-actions.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts
=> refactor(actions):  use structuredResponse

apps/web/src/app/[lang]/app/[type]/profile/[profileId]/form.tsx
=> feat: remove confirm dialog

apps/web/src/app/[lang]/app/[type]/settings/templates/refund-fees/page.tsx, apps/web/src/app/[lang]/app/actions/ContractService/action.ts, apps/web/src/app/[lang]/app/actions/ContractService/put-actions.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts, apps/web/src/language-data/Default/resources/en.json, apps/web/src/language-data/Default/resources/tr.json
=> feat(api-request): add putRefundFeeHeadersApi & rename actions & add translations

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/contract-settings.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/contract-widgets.tsx, apps/web/src/app/[lang]/app/actions/CrmService/actions.ts, apps/web/src/language-data/ContractService/resources/en.json, apps/web/src/language-data/ContractService/resources/tr.json
=> feat(Contracts): contract widgets & subMerchant actions & language

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/details.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/rebate-settings.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/contract-header-form.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/rebate-form.tsx
=> feat(Contract/RebateSettings): rebatesettings form

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/[section]/rebate-settings/rebate-settings-page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/[section]/rebate-settings/rebate-settings.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/rebate-form.tsx, apps/web/src/app/[lang]/app/actions/ContractService/post-actions.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts, apps/web/src/language-data/ContractService/resources/en.json, apps/web/src/language-data/ContractService/resources/tr.json
=> feat(Contract/RebateSetting): handle post rebate settings 

apps/web/src/app/[lang]/app/actions/api-utils-client.ts
=> feat(ApiUtils): redirect based on response option

apps/web/src/app/[lang]/app/[type]/navbar/navbar-data.tsx
=> fix(navbar): missing nav items

apps/web/package.json, apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/identification/[identificationId]/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/identification/new/form.tsx, apps/web/src/app/[lang]/app/actions/CrmService/actions.ts, apps/web/src/app/[lang]/app/actions/TravellerService/put-actions.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts, pnpm-lock.yaml
=> chore(saas): update crm service & remove unused actions

apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/identification/[identificationId]/form.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/identification/[identificationId]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/traveller/[travellerId]/identification/new/form.tsx, apps/web/src/app/[lang]/app/actions/TravellerService/post-actions.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts, apps/web/src/app/[lang]/app/actions/api-utils-client.ts
=> refactor(traveller): edit the forms of edit and new identification

apps/web/src/app/[lang]/app/actions/api-utils-client.ts
=> feat: api utils make router optional

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/[section]/contract/contract-header.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/contract-header-form.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/new/page.tsx, apps/web/src/language-data/ContractService/resources/en.json, apps/web/src/language-data/ContractService/resources/tr.json
=> feat(Contracts): contract actions & form loading handle

apps/web/src/app/[lang]/app/actions/ContractService/action.ts, apps/web/src/app/[lang]/app/actions/api-requests.ts
=> feat(Contract): stores api enpoints

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/[section]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/[section]/stores/page.tsx, apps/web/src/language-data/ContractService/resources/en.json, apps/web/src/language-data/ContractService/resources/tr.json
=> feat(Contract/Store): page entry point

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/[section]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/[section]/stores/_components/table-data.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/[section]/stores/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/[section]/stores/table.tsx
=> feat(Contract/Stores): get contract stores & list on table

apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/page.tsx, apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/table-actions/claims.tsx
=> feat(management/claims): make the autoform be closed after submit

apps/web/src/app/[lang]/app/[type]/finance/billing/[billingId]/form.tsx, apps/web/src/app/[lang]/app/[type]/finance/billing/new/form.tsx, apps/web/src/app/[lang]/app/[type]/operations/export-validation/[exportId]/form.tsx, apps/web/src/app/[lang]/app/[type]/operations/export-validation/new/form.tsx
=> refactor(exportValidation/Billing): make the form be as 2 side

apps/web/src/app/[lang]/app/[type]/finance/billing/table-data.tsx
=> fix(billing): remove exclude list

apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/rebate-form.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-fees/[id]/table.tsx
=> chore:update ui

apps/web/src/app/[lang]/app/[type]/parties/customs/customs-table-data.tsx, apps/web/src/app/[lang]/app/[type]/parties/customs/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/customs/table.tsx, apps/web/src/app/[lang]/app/[type]/parties/individuals/individuals-table-data.tsx, apps/web/src/app/[lang]/app/[type]/parties/individuals/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/individuals/table.tsx, apps/web/src/app/[lang]/app/[type]/parties/merchants/merchant-table-data.tsx, apps/web/src/app/[lang]/app/[type]/parties/merchants/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/merchants/table.tsx, apps/web/src/app/[lang]/page-policy/action-policy.tsx
=> feat(permission): parties use new table and permission checks for actions

apps/web/src/app/[lang]/app/[type]/parties/refund-points/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/refund-points/refund-points-table-data.tsx, apps/web/src/app/[lang]/app/[type]/parties/refund-points/table.tsx, apps/web/src/app/[lang]/app/[type]/parties/tax-free/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/tax-free/table.tsx, apps/web/src/app/[lang]/app/[type]/parties/tax-free/tax-free-table-data.tsx, apps/web/src/app/[lang]/app/[type]/parties/tax-offices/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/tax-offices/table.tsx, apps/web/src/app/[lang]/app/[type]/parties/tax-offices/tax-offices-table-data.tsx
=> feat(permission): use new table and permission checks for action

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/contract/_components/contract-header.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/_components/contract-header-form/merchant/index.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/_components/contract-header-form/refund-point/index.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/_components/table-data.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/_components/types.ts, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/new/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/table.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/page.tsx
=> refactor(ContractHeader): split forms by partyType

packages/ui/package.json
=> chore:remove build from ui

.github/workflows/publish-dev.yml
=> chore:update yaml

apps/web/next-env.d.ts, apps/web/next.config.js, apps/web/package.json, apps/web/tsconfig.json, pnpm-lock.yaml
=> chore(nextjs): update nextjs to 14.2.20 from 14.1.1

apps/web/src/app/[lang]/app/actions/api-requests.ts, apps/web/src/lib.ts
=> refactor(lib): performance improvements on api calls

apps/web/auth-action.ts, apps/web/package.json, apps/web/src/app/api/auth/reset-password/route.ts, apps/web/src/app/api/auth/send-password-reset-code/route.ts, packages/ui/package.json, pnpm-lock.yaml
=> chore(saas): update saas & chore(password-reset): add tenant

apps/web/src/app/[lang]/app/[type]/navbar/navbar-data.tsx, apps/web/src/app/[lang]/app/[type]/operations/details/[tagId]/_components/merchant-details.tsx, apps/web/src/app/[lang]/app/[type]/operations/details/[tagId]/_components/traveller-details.tsx
=> fix(page description): no description & fix imports

apps/web/src/app/[lang]/app/[type]/settings/templates/refund-fees/[id]/form.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-fees/[id]/table.tsx
=> feat(Templates/RefundFee): clear table fields & scroll issue

apps/web/auth.ts
=> fix(#977): granted policies not coming when first logged in

apps/web/src/app/[lang]/app/[type]/home/page.tsx
=> chore: remove upwithcrowd related pages closes #966

apps/web/src/language-data/ContractService/resources/en.json, apps/web/src/language-data/ContractService/resources/tr.json
=> feat(Contracts/RefundPoint): languages

apps/web/src/app/[lang]/app/[type]/settings/tenant/[group]/_components/utils.ts, apps/web/src/app/[lang]/app/[type]/settings/tenant/[group]/group.tsx
=> fix: tenant settings default value & default group

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/_components/contract-widgets.tsx
=> feat: refundFee widget for future use

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/page.tsx
=> fix: invalid if statement for contract page

apps/web/src/app/[lang]/app/actions/ContractService/action.ts
=> feat: get rebateSettings action

apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/table-actions/permissions.tsx
=> refactor(permissions): enhance the functions without useing usestate inside each other

apps/web/src/app/[lang]/app/[type]/not-found.tsx, apps/web/src/app/[lang]/app/[type]/refund/page.tsx, apps/web/src/app/[lang]/page-policy/page-policy.tsx, apps/web/src/app/[lang]/unauthorized/page.tsx
=> feat(unauthorized): add missing unauthorized page & use

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/_components/contract-header-form/refund-point/index.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/new/page.tsx
=> feat(Contracts-RefundPoint): contract header form for refund points

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/contract-settings/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/contract/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/layout.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/rebate-settings/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/stores/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/new/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/customs/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/individuals/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/merchants/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/refund-points/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/tax-free/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/tax-offices/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/travellers/[travellerId]/identification/[identificationId]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/travellers/[travellerId]/identification/new/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/travellers/[travellerId]/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/travellers/new/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/travellers/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/rebate/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-fees/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-fees/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-tables/[id]/page.tsx, apps/web/src/app/[lang]/app/[type]/settings/templates/refund-tables/page.tsx
=> refactor(refund): use  isUnauthorized function instread of pagePolicy

apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/contract/_components/merchant/index.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/contract/_components/refund-point/index.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/contract/page.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/[contractId]/layout.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/_components/contract-header-form/merchant/index.tsx, apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/contracts/new/page.tsx
=> feat(ContractRefundPoint): contract header form for edit

apps/web/src/app/[lang]/layout.tsx, apps/web/src/utils/navbar/navbar-data.tsx
=> chore(navbar): something

apps/web/src/app/page.tsx, apps/web/src/middleware.ts, apps/web/src/utils/navbar/core-navbar-items.json
=> fix(middleware):

apps/web/src/app/[lang]/(core)/settings/tenant/page.tsx
=> chore(settings): fix page link

apps/web/.eslintrc.js, apps/web/src/app/[lang]/(main)/(core)/home/page.tsx, apps/web/src/app/[lang]/(main)/error.tsx
=> chore(eslint): disable explicit-function-return-type rule

apps/web/auth-action.ts, apps/web/auth.ts, apps/web/src/app/[lang]/(main)/layout.tsx, packages/ui/src/providers/theme.tsx, packages/ui/src/theme/main-admin-layout/components/logo.tsx, packages/ui/src/theme/main-admin-layout/components/navbar.tsx, packages/ui/src/theme/main-admin-layout/header-section.tsx, packages/ui/src/theme/main-admin-layout/index.tsx
=> feat(tenant): show tenant information next to logo

apps/web/src/actions/core/AccountService/delete-actions.ts, apps/web/src/actions/core/AccountService/post-actions.ts, apps/web/src/actions/core/AccountService/put-actions.ts, apps/web/src/app/[lang]/(main)/(core)/account/change-password/page.tsx, apps/web/src/app/[lang]/(main)/(core)/account/personal-information/page.tsx, apps/web/src/app/[lang]/(main)/(core)/account/profile-picture/page.tsx, apps/web/src/app/[lang]/(main)/(core)/account/security-logs/page.tsx, apps/web/src/app/[lang]/(main)/(core)/account/security-logs/security-logs-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/account/security-logs/table.tsx, apps/web/src/app/[lang]/(main)/(core)/account/sessions/_components/details-information.tsx, apps/web/src/app/[lang]/(main)/(core)/account/sessions/page.tsx, apps/web/src/app/[lang]/(main)/(core)/account/sessions/sessions-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/account/sessions/table.tsx
=> feat(profile): add sessions & security logs

apps/web/package.json, apps/web/src/actions/api-requests.ts, apps/web/src/actions/core/IdentityService/actions.ts, packages/ui/package.json, pnpm-lock.yaml
=> chore: add missing actions to identity

apps/web/src/utils/navbar/core-navbar-items.json, apps/web/src/utils/navbar/groups.tsx
=> chore: add permssion to main list

apps/web/src/utils/navbar/core-navbar-items.json, apps/web/src/utils/navbar/groups.tsx
user with tenant
admin without tenant
=> chore(permission): fix permission in main list

apps/web/src/app/[lang]/(main)/(core)/management/[domain]/[data]/client.tsx, apps/web/src/app/[lang]/(main)/(core)/management/[domain]/[data]/page.tsx
=> feat(management/permission): add permission in pages

apps/web/src/providers/granted-policies.tsx
=> fix: granted policies problems

apps/web/src/types.ts
=> feat(types): add Optional type for partial object handling

apps/web/src/app/[lang]/(main)/(core)/management/text-templates/_components/table.tsx, apps/web/src/app/[lang]/(main)/(core)/management/text-templates/_components/text-template-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/text-templates/page.tsx
=> feat(text template): add text template page

apps/web/src/app/[lang]/(main)/(core)/management/audit-logs/_components/audit-logs-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/audit-logs/_components/table.tsx, apps/web/src/app/[lang]/(main)/(core)/management/audit-logs/page.tsx
=> feat(auditLogs): add auditLogs page

apps/web/src/app/[lang]/(main)/(core)/management/language-management/language-texts/_components/language-texts-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/language-texts/_components/table.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/language-texts/page.tsx
=> feat(Langugae Text): add Langugae Text page

apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/[languageId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/[languageId]/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/_components/languages-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/_components/table.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/new/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/page.tsx, apps/web/src/language-data/core/AdministrationService/resources/en.json, apps/web/src/language-data/core/AdministrationService/resources/tr.json
=> feat(langugae): add langugae page

apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/[tenantId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/[tenantId]/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/[tenantId]/set-password/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/[tenantId]/set-password/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/_components/table.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/_components/tenants-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/new/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/page.tsx, apps/web/src/language-data/core/SaasService/resources/en.json, apps/web/src/language-data/core/SaasService/resources/tr.json
=> feat(tenant): add tenant main page & new & edit & set password forms

apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/[editionId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/[editionId]/move-all-tenants/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/[editionId]/move-all-tenants/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/[editionId]/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/_components/editions-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/_components/table.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/new/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/page.tsx
=> feat(edition): add edition main page & new & edit & move all tenant forms

apps/web/src/app/layout.tsx, apps/web/src/language-data/core/AbpUiNavigation/index.ts, apps/web/src/providers/auth.tsx, apps/web/src/providers/providers.tsx, apps/web/src/utils.ts
=> feat(auth): integrate session management and enhance provider 

apps/web/src/app/[lang]/(main)/(core)/management/identity/security-logs/_components/security-logs-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/security-logs/_components/table.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/security-logs/page.tsx
=> feat(security Logs):add security logs page

apps/web/src/app/[lang]/(main)/(core)/management/identity/claim-types/[claimTypeId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/claim-types/[claimTypeId]/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/claim-types/_components/claim-types-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/claim-types/_components/table.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/claim-types/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/claim-types/new/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/claim-types/page.tsx
=> feat(CliamsType): add CliamsType main page & create & edit forms

apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/[roleId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/[roleId]/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/_components/roles-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/_components/table.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/new/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/page.tsx
=> feat(roles): add roles main page & create & edit forms

apps/web/src/app/[lang]/(main)/(core)/management/openiddict/scopes/[scopeId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/scopes/[scopeId]/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/scopes/_components/scopes-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/scopes/_components/table.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/scopes/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/scopes/new/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/scopes/page.tsx
=> feat(scopes): add scope main page & create & edit forms

apps/web/src/app/layout.tsx, apps/web/src/providers/providers.tsx, apps/web/src/providers/session.tsx
=> refactor(session): remove sessionKey prop and generate key internally

apps/web/src/utils.ts
=> feat: update localization resource fetching to use API endpoint

apps/web/src/app/[lang]/(main)/(core)/management/identity/organization/action.ts, apps/web/src/app/[lang]/(main)/(core)/management/identity/organization/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/organization/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/new/_components/form.tsx
=> feat(organization): add page and fix role options

apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/_components/applications-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/_components/table.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/page.tsx
=> feat(application): add mian table

apps/web/next.config.js
=> fix:transpile core package 

packages/utils/api/index.ts, packages/utils/policies/utils.ts
=> refactor: simplify error handling in API response and remove unused code

packages/utils/auth/actions.ts, packages/utils/auth/index.tsx
=> refactor: rename index.ts to actions.ts and update exports

apps/web/package.json, apps/web/src/app/[lang]/(main)/(core)/settings/tenant/[group]/_components/utils.ts, apps/web/src/app/[lang]/(main)/(core)/settings/tenant/[group]/group.tsx, apps/web/src/app/[lang]/(main)/(core)/settings/tenant/[group]/mock-settings-response.ts, pnpm-lock.yaml
=> chore(setting): update setting service & fix the error

apps/web/src/actions/core/AccountService/post-actions.ts
=> feat(account) add SendPasswordResetCode backend function

apps/web/src/actions/core/IdentityService/put-actions.ts
=> feat(user): add backend functions

apps/web/.env.example, apps/web/src/actions/core/AccountService/actions.ts, apps/web/src/app/[lang]/(main)/layout.tsx, apps/web/src/app/api/auth/[...nextauth]/route.ts, apps/web/src/app/layout.tsx, apps/web/src/lib.ts, apps/web/src/middleware.ts, packages/utils/auth/auth-actions.ts, packages/utils/auth/auth-types.ts, packages/utils/auth/auth.ts, packages/utils/auth/index.tsx, packages/utils/package.json
=> feat: auth 

turbo.json
=> chore:turbo env

apps/web/src/app/[lang]/(main)/layout.tsx, packages/utils/auth/auth.ts
=> fix: update tenant data handling and improve error logging in auth

apps/web/src/app/layout.tsx, apps/web/src/providers/providers.tsx, packages/utils/policies/granted-policies.tsx
=> fix(auth): granted policies not coming on first login

apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/[applicationId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/[applicationId]/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/new/page.tsx
=> feat(application): add create & edit forms of application page

apps/web/src/app/[lang]/(main)/(core)/management/identity/claim-types/[claimTypeId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/claim-types/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/[roleId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/[roleId]/permissions/_components/permissions.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/permissions/_components/permissions.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/[languageId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/scopes/[scopeId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/scopes/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/[editionId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/[tenantId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/new/_components/form.tsx
=> refactor(management): use router.push inside the handle functions

apps/web/src/app/layout.tsx, packages/ui/src/theme/main-admin-layout/header-section.tsx
=> refactor(layout): wrap Providers in Suspense for improved loading state & dynamic page header

apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/[applicationId]/life-token/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/[applicationId]/permissions/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/new/page.tsx
=> fix(applications): change the names to be correct

apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/[roleId]/permissions/_components/permissions.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/permissions/_components/permissions.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/[applicationId]/permissions/_components/permissions.tsx
=> fix(permissions): change the link to return after submit

apps/web/src/actions/core/AccountService/actions.ts
=> fix(account): include tenant in password reset code request

apps/web/src/app/[lang]/(main)/(core)/management/identity/organization/organization.tsx
=> feat(organization): add edit & create sub unit & move all users & delete  options

apps/web/src/actions/core/AdministrationService/actions.ts, apps/web/src/actions/core/AdministrationService/put-actions.ts, apps/web/src/app/[lang]/(main)/(core)/management/language-management/language-texts/_components/language-text-edit.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/language-texts/_components/language-texts-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/language-texts/_components/table.tsx, apps/web/src/language-data/core/AdministrationService/resources/en.json, apps/web/src/language-data/core/AdministrationService/resources/tr.json
=> feat(language text):add edit value & restore to defualt value actions

apps/web/src/app/[lang]/(main)/(core)/management/language-management/language-texts/_components/language-text-edit.tsx
=> refactor(language text): add textarea to fields

apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/lock/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/lock/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/_components/users-table-data.tsx, apps/web/src/language-data/core/IdentityService/resources/en.json, apps/web/src/language-data/core/IdentityService/resources/tr.json
=> feat(users): add lock & unlock actions

apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/[roleId]/permissions/_components/permissions.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/permissions/_components/permissions.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/[applicationId]/permissions/_components/permissions.tsx, pnpm-lock.yaml
=> chore(permissions): enhance view

apps/web/.eslintrc.js, apps/web/src/actions/core/IdentityService/actions.ts, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/new/page.tsx, packages/utils/api/action.ts
=> refactor(user): use al roles function instead of assinable role function

apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/_components/form.tsx, apps/web/src/language-data/core/AbpUiNavigation/resources/en.json, apps/web/src/language-data/core/AbpUiNavigation/resources/tr.json
=> chore: fix some errors & add translation

apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/new/_components/form.tsx
=> fix(user): send the name of role instead id

apps/web/src/language-data/core/AbpUiNavigation/resources/en.json, apps/web/src/language-data/core/AbpUiNavigation/resources/tr.json
=> chore: add translation

apps/web/src/app/[lang]/(main)/(core)/management/identity/users/_components/users-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/_components/languages-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/text-templates/_components/text-template-table-data.tsx
=> fix: change the true  & false to icons in table

packages/ui/src/theme/main-admin-layout/components/breadcrumb/index.tsx
=> refactor(breadcrumb): show child nav items in sub nav item

apps/web/src/utils/navbar/core-navbar-items.json, packages/ui/src/theme/main-admin-layout/components/navbar.tsx
=> feat: add new role and user management options to navbar

apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/[roleId]/permissions/_components/permissions.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/permissions/_components/permissions.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/[applicationId]/permissions/_components/permissions.tsx, apps/web/src/language-data/core/IdentityService/resources/en.json, apps/web/src/language-data/core/IdentityService/resources/tr.json
=> feat(managements/permissions): add grop & permissions filter

apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/new/_components/form.tsx
=> feat(user): add phone input & use new system

packages/ui/.eslintrc.js, packages/ui/package.json, packages/ui/src/TableComponent/index.tsx, packages/ui/src/logo/index.tsx, packages/ui/src/providers/theme.tsx, packages/ui/src/select-merchant/index.tsx, packages/ui/src/sortable-layout/index.tsx, packages/ui/src/theme/breadcrumb-navigation/index.tsx, packages/ui/src/theme/main-admin-layout/components/language-selector/index.tsx, packages/ui/src/theme/main-admin-layout/components/logo.tsx, packages/ui/src/theme/main-admin-layout/components/navbar-dropdown/index.tsx, packages/ui/src/theme/main-admin-layout/components/navbar-searchbar/index.tsx, packages/ui/src/theme/main-admin-layout/components/notifications/index.tsx, packages/ui/src/theme/main-admin-layout/components/profile-menu/index.tsx, packages/ui/src/theme/main-admin-layout/header-section.tsx, packages/ui/src/theme/main-admin-layout/index.tsx, packages/ui/src/theme/types/index.tsx, packages/ui/src/toast-on-submit/index.tsx, packages/ui/src/utils.ts, packages/ui/tailwind.config.ts, packages/ui/tsconfig.json, packages/ui/utils/general/globalFetch.ts, packages/ui/utils/table/form-schemas.ts, packages/ui/utils/table/table-utils.ts
=> refactor: format code for consistency and improve readability

apps/web/src/utils/navbar/core-navbar-items.json
=> feat: update required policies for identity and management navbar items to include create permissions

apps/web/src/app/[lang]/(main)/(core)/account/change-password/change-passwod.tsx, apps/web/src/app/[lang]/(main)/(core)/account/personal-information/personal-information.tsx, apps/web/src/app/[lang]/(main)/(core)/account/profile-picture/personal-picture.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/claim-types/[claimTypeId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/claim-types/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/[roleId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/[roleId]/assignable-roles/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/[roleId]/claims/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/[roleId]/move-all-users/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/claims/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/lock/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/set-password/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/[userId]/two-factor/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/language-texts/_components/language-text-edit.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/[languageId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/[applicationId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/[applicationId]/life-token/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/scopes/[scopeId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/scopes/new/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/[editionId]/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/[editionId]/move-all-tenants/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/new/_components/form.tsx
=> refactor(core): replace loading state with useTransition for improved UI responsiveness

readme/SERVER_SIDE_README.md
=> docs(server-side): update readme

apps/web/src/actions/core/AccountService/actions.ts, apps/web/src/app/[lang]/(main)/layout.tsx, apps/web/src/app/layout.tsx, apps/web/src/middleware.ts, apps/web/src/providers/providers.tsx, packages/ui/src/theme/auth/login/index.tsx, packages/utils/policies/granted-policies.tsx
=> fix(granted-policies) & fix(redirect from middleware) & use next redirect to login

packages/ui/src/theme/auth/login/index.tsx, packages/utils/auth/auth-actions.ts
=> refactor(login): improve redirect logic and clean up code formatting

apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/[editionId]/features/_components/form.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/[editionId]/features/page.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/_components/editions-table-data.tsx
=> feat(editions): add feature management  page 

apps/web/src/app/[lang]/(main)/layout.tsx, apps/web/src/app/[lang]/layout.tsx, apps/web/src/providers/providers.tsx
=> feat: implement root layout and enhance notification subscriber handling

apps/web/src/app/[lang]/(main)/layout.tsx, apps/web/src/providers/novu.tsx, apps/web/src/providers/providers.tsx, apps/web/src/utils/navbar/notification.tsx
=> fix(novu): handle missing env variable in Novu components

apps/web/src/language-data/core/Default/resources/tr.json, packages/ui/src/theme/main-admin-layout/components/notifications/index.tsx, packages/ui/src/theme/types/index.tsx
=> refactor(notifications): clean up notification component structure and styles

apps/web/package.json, apps/web/src/providers/providers.tsx, packages/ui/package.json, packages/ui/src/providers/novu.tsx, pnpm-lock.yaml
=> chore: remove @novu/react dependency and add NovuProvider component

apps/web/package.json, packages/ui/src/components/error-component.tsx, pnpm-lock.yaml
…component from ErrorComponent## Description
=> chore: add @tailwindcss/typography dependency and remove unused Logo from ErrorComponent

packages/utils/auth/middleware.ts
=> feat(middleware): add handling for next-action header in middleware

packages/ui/package.json, packages/ui/src/utils.ts
=> feat(ui): add formatCurrency utility function and update exports

packages/ui/src/components/error-component.tsx
=> feat(ui): add home button functionality to ErrorComponent with sign-out handlin

packages/actions/core/NovuService/actions.ts, packages/actions/package.json, pnpm-lock.yaml
=> feat(novu): implement notification triggering functionality

apps/web/src/language-data/core/Default/resources/en.json, apps/web/src/language-data/core/Default/resources/tr.json, packages/actions/core/NovuService/actions.ts
=> feat(i18n): add error and workflow-related messages 

packages/actions/core/AccountService/actions.ts
=> fix(actions): improve error handling in signUpServerApi function

apps/web/src/language-data/core/IdentityService/index.ts
=> chore: update IdentityService resource type and subproject commit reference

apps/web/get-resources.js, apps/web/package.json
=> feat: update resource script to load environment variables and silence prettier logs

apps/web/get-resources.js
=> fix: restructure main function to improve error handling for resource updates

packages/actions/core/NovuService/actions.ts
=> fix: add functions to retrieve single and list notifications from Novu

apps/web/src/app/[lang]/(main)/(core)/management/identity/claim-types/_components/claim-types-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/roles/_components/roles-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/identity/users/_components/users-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/language-management/languages/_components/languages-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/applications/_components/applications-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/openiddict/scopes/_components/scopes-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/editions/_components/editions-table-data.tsx, apps/web/src/app/[lang]/(main)/(core)/management/saas/tenants/_components/tenants-table-data.tsx, pnpm-lock.yaml
=> feat:update table type due ui update

apps/web/src/language-data/core/AccountService/resources/en.json, apps/web/src/language-data/core/AccountService/resources/tr.json, packages/ui/src/theme/auth/login/index.tsx
=> feat:update login form

apps/web/src/language-data/core/Default/resources/en.json, apps/web/src/language-data/core/Default/resources/tr.json
=> chore:add lang

apps/web/package.json, apps/web/src/language-data/resources.ts, apps/web/src/providers/tenant.tsx, pnpm-lock.yaml
=> chore: tenant setings
